local_homepage:
    path:     /
    defaults: { _controller: LocalBundle:Default:index }

ajout_local:
    path:     /ajout
    defaults: { _controller: LocalBundle:Default:ajout }

all_local:
    path:     /locaux{id}
    defaults: { _controller: LocalBundle:Default:locaux }

succes:
    path:     /ajout/succes
    defaults: { _controller: LocalBundle:Default:succes }

delete_local:
    path:     /loacaux/delete{id}
    defaults: { _controller: LocalBundle:Default:delete }

modifier_local:
    path:     /modifier{id}
    defaults: { _controller: LocalBundle:Default:modifier }

