produit_homepage:
    path:     /
    defaults: { _controller: ProduitBundle:Default:index }

tout_produit:
    path:     /produits{ref}
    defaults: { _controller: ProduitBundle:Default:produits }

ajout_produit:
    path:     /add
    defaults: { _controller: ProduitBundle:Default:add }

valide:
    path:     /add/valide
    defaults: { _controller: ProduitBundle:Default:valide }

affichage:
    path:     /afficher
    defaults: { _controller: ProduitBundle:Default:afficherProduit }
